# Generated by Django 5.2.9 on 2026-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
