# Generated by Django 5.2.9 on 2026-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
