# Generated by Django 5.2.9 on 2026-01-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_full_name_enrollment_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
