# Generated by Django 5.2.9 on 2026-01-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
