# Generated by Django 5.2.9 on 2026-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_unique_together_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web-development', 'Web Development'), ('mobile-development', 'Mobile Development'), ('data-science', 'Data Science'), ('artificial-intelligence', 'Artificial Intelligence'), ('cloud-computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('design', 'Design'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
