# Generated by Django 5.2.9 on 2026-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_options_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('web-development', 'Web Development'), ('mobile-development', 'Mobile Development'), ('data-science', 'Data Science'), ('artificial-intelligence', 'Artificial Intelligence'), ('cloud-computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('design', 'Design'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
